# Generated by hand to add credit_days to Supplier
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='credit_days',
            field=models.IntegerField(default=0),
        ),
    ]