# Generated by Django 4.2.23 on 2025-09-13 14:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_supplier_credit_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clearance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('discount', 'Discount %'), ('flat', 'Flat Price'), ('bogo', 'Buy X Get Y'), ('bundle', 'Bundle')], max_length=20)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bogo_buy_x', models.PositiveIntegerField(default=1)),
                ('bogo_get_y', models.PositiveIntegerField(default=1)),
                ('expires_at', models.DateTimeField()),
                ('generated_sku', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('generated_barcode', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearance_deals', to='inventory.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'created_by')},
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('name', 'created_by')},
        ),
        migrations.CreateModel(
            name='ClearanceBundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('clearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='inventory.clearance')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_in_clearances', to='inventory.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
