# Generated by Django 4.2.23 on 2025-09-13 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_purchaseorder_buyer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='buyer_name',
        ),
    ]
