# Generated by Django 4.2.23 on 2025-08-19 15:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supermarket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('business_license', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='supermarket_logos/')),
                ('is_sub_store', models.BooleanField(default=False)),
                ('pos_system_type', models.CharField(choices=[('SQUARE', 'Square'), ('SHOPIFY', 'Shopify'), ('CUSTOM', 'Custom'), ('NONE', 'None')], default='NONE', max_length=20)),
                ('pos_system_enabled', models.BooleanField(default=False)),
                ('pos_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('pos_api_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('pos_store_id', models.CharField(blank=True, max_length=100, null=True)),
                ('pos_sync_enabled', models.BooleanField(default=False)),
                ('last_pos_sync', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_supermarkets', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_stores', to='supermarkets.supermarket')),
            ],
            options={
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='SupermarketSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_stock_alert_enabled', models.BooleanField(default=True)),
                ('expiry_alert_enabled', models.BooleanField(default=True)),
                ('expiry_alert_days', models.IntegerField(default=7)),
                ('daily_report_enabled', models.BooleanField(default=False)),
                ('weekly_report_enabled', models.BooleanField(default=True)),
                ('monthly_report_enabled', models.BooleanField(default=True)),
                ('auto_reorder_enabled', models.BooleanField(default=False)),
                ('default_min_stock_level', models.IntegerField(default=5)),
                ('barcode_generation_enabled', models.BooleanField(default=True)),
                ('auto_sync_interval', models.IntegerField(default=60, help_text='Minutes between auto syncs')),
                ('sync_price_changes', models.BooleanField(default=True)),
                ('sync_stock_changes', models.BooleanField(default=True)),
                ('sync_new_products', models.BooleanField(default=True)),
                ('products_per_page', models.IntegerField(default=20)),
                ('default_currency_symbol', models.CharField(default='$', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supermarket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='supermarkets.supermarket')),
            ],
        ),
        migrations.CreateModel(
            name='SupermarketInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('MANAGER', 'Manager'), ('ASSISTANT_MANAGER', 'Assistant Manager'), ('CASHIER', 'Cashier'), ('STOCK_CLERK', 'Stock Clerk'), ('SECURITY', 'Security'), ('CLEANER', 'Cleaner'), ('OTHER', 'Other')], max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('can_manage_inventory', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('can_manage_pos', models.BooleanField(default=False)),
                ('can_manage_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('supermarket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='supermarkets.supermarket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupermarketStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MANAGER', 'Manager'), ('ASSISTANT_MANAGER', 'Assistant Manager'), ('CASHIER', 'Cashier'), ('STOCK_CLERK', 'Stock Clerk'), ('SECURITY', 'Security'), ('CLEANER', 'Cleaner'), ('OTHER', 'Other')], max_length=20)),
                ('hire_date', models.DateField()),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('can_manage_inventory', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('can_manage_pos', models.BooleanField(default=False)),
                ('can_manage_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supermarket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='supermarkets.supermarket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('supermarket', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SupermarketAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_products', models.IntegerField(default=0)),
                ('total_inventory_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('low_stock_products', models.IntegerField(default=0)),
                ('expired_products', models.IntegerField(default=0)),
                ('expiring_soon_products', models.IntegerField(default=0)),
                ('products_added', models.IntegerField(default=0)),
                ('products_removed', models.IntegerField(default=0)),
                ('stock_adjustments', models.IntegerField(default=0)),
                ('pos_sync_count', models.IntegerField(default=0)),
                ('pos_sync_errors', models.IntegerField(default=0)),
                ('last_pos_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supermarket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='supermarkets.supermarket')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('supermarket', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='supermarket',
            index=models.Index(fields=['owner'], name='supermarket_owner_i_103aaa_idx'),
        ),
        migrations.AddIndex(
            model_name='supermarket',
            index=models.Index(fields=['is_active'], name='supermarket_is_acti_d15854_idx'),
        ),
        migrations.AddIndex(
            model_name='supermarket',
            index=models.Index(fields=['is_sub_store'], name='supermarket_is_sub__079e04_idx'),
        ),
    ]
