# Generated by Django 6.0.1 on 2026-05-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LOW_STOCK', 'Low Stock Alert'), ('EXPIRY', 'Expiry Alert'), ('OUT_OF_STOCK', 'Out of Stock'), ('POS_SYNC', 'POS Sync Update'), ('REPORT_READY', 'Report Ready'), ('FILE_PROCESSED', 'File Processed'), ('SYSTEM', 'System Notification'), ('WELCOME', 'Welcome Message'), ('SUBSCRIPTION', 'Subscription Update'), ('ORDER_DELIVERED', 'Order Delivered'), ('ORDER_LATE', 'Order Late')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('LOW_STOCK', 'Low Stock Alert'), ('EXPIRY', 'Expiry Alert'), ('OUT_OF_STOCK', 'Out of Stock'), ('POS_SYNC', 'POS Sync Update'), ('REPORT_READY', 'Report Ready'), ('FILE_PROCESSED', 'File Processed'), ('SYSTEM', 'System Notification'), ('WELCOME', 'Welcome Message'), ('SUBSCRIPTION', 'Subscription Update'), ('ORDER_DELIVERED', 'Order Delivered'), ('ORDER_LATE', 'Order Late')], max_length=20),
        ),
    ]
